events {}

http {
  upstream frontend {
    server frontend:80;
  }

  upstream monolith_backend {
    server backend:3000;
  }

  server {
    listen 8080;

    location /api/auth/ {
      proxy_pass http://monolith_backend/auth/;
    }

    location /api/shoes/ {
      proxy_pass http://monolith_backend/shoes/;
    }

    location /api/inventory/ {
      proxy_pass http://monolith_backend/inventory/;
    }

    location /api/payments/ {
      proxy_pass http://monolith_backend/payments/;
    }

    location /api/coupons/ {
      proxy_pass http://monolith_backend/coupons/;
    }

    location /api/chat/ {
      proxy_pass http://monolith_backend/chat/;
    }

    location /api/reviews/ {
      proxy_pass http://monolith_backend/reviews/;
    }

    location /api/returns/ {
      proxy_pass http://monolith_backend/returns/;
    }

    location / {
      proxy_pass http://frontend;
    }
  }
}
