# Use Case XML Generator
# Generates 68 individual XML files for each use case

$BASE = "docs\requirements\usecases"

$ucs = @(
  @{id="UC-01"; name="Browse Products"; actors="Guest;User;Manager;Admin"; priority="High"; pre="Không có"; post="Danh sách sản phẩm hiển thị"; flow="1. User truy cập trang chủ hoặc trang /all-shoes@2. System gọi API GET /shoes@3. System trả về danh sách sản phẩm (name, price, thumbnail, colorName, rating, reviewCount)@4. Frontend render product cards với lazy loading"; altFlow="2a. API lỗi -> hiển thị error state"; category="Browsing & Discovery"},
  @{id="UC-02"; name="Search/Filter Products"; actors="Guest;User;Manager;Admin"; priority="High"; pre="Đang ở trang product listing"; post="Danh sách sản phẩm được lọc"; flow="1. User chọn filter: category, color, price range, size@2. System gọi API GET /shoes?category=men&color=Black&minPrice=50&maxPrice=150@3. System trả về filtered results@4. User có thể nhập text search vào thanh tìm kiếm@5. System gọi API GET /shoes?search=Air+Max"; altFlow="3a. Không có kết quả -> hiển thị empty state"; category="Browsing & Discovery"},
  @{id="UC-03"; name="View Product Detail"; actors="Guest;User;Manager;Admin"; priority="High"; pre="Có productId hợp lệ"; post="Trang chi tiết sản phẩm hiển thị"; flow="1. User click vào 1 sản phẩm@2. System gọi API GET /shoes/detail/:productId@3. System trả về: name, category, price, colors[], images[], sizes[], description, materialNote, origin, rating, reviewCount@4. Frontend hiển thị image gallery, color picker, size picker, stock indicator@5. System đồng thời gọi GET /reviews/product/:productId để hiển thị reviews"; altFlow="2a. productId không tồn tại -> 404 page"; category="Browsing & Discovery"},
  @{id="UC-04"; name="Check Stock Real-time"; actors="Guest;User;Manager;Admin"; priority="High"; pre="Đang ở trang product detail"; post="Hiển thị số lượng tồn kho của size đã chọn"; flow="1. User chọn color + size@2. System gọi API GET /shoes/:productId/stock/:colorName/:size@3. System trả về { stock: 5 }@4. UI hiển thị 'Còn hàng' (xanh) hoặc 'Hết hàng' (đỏ)"; altFlow="3a. Size hết hàng -> disable nút 'Add to Cart'"; category="Browsing & Discovery"},
  @{id="UC-05"; name="View Reviews"; actors="Guest;User;Manager;Admin"; priority="Medium"; pre="Đang ở trang product detail"; post="Danh sách reviews hiển thị"; flow="1. User scroll xuống phần reviews của product detail@2. System gọi API GET /reviews/product/:productId@3. System trả về danh sách reviews (rating, comment, images, user, createdAt)@4. UI hiển thị star rating trung bình và danh sách reviews"; altFlow="3a. Chưa có review -> hiển thị 'Be the first to review'"; category="Browsing & Discovery"},
  @{id="UC-06"; name="Add Product to Cart"; actors="Guest;User"; priority="High"; pre="Đang ở trang product detail, đã chọn color + size, còn hàng"; post="Sản phẩm được thêm vào giỏ hàng"; flow="1. User chọn quantity (mặc định: 1)@2. User bấm 'Add to Bag'@3. System kiểm tra stock lần nữa@4. System thêm item vào cart state (Pinia store)@5. System lưu cart vào localStorage (cho guest)@6. Toast notification: 'Added to bag'"; altFlow="3a. Stock không đủ -> hiển thị lỗi@4a. Sản phẩm đã có trong cart -> tăng quantity (nếu còn stock)"; category="Shopping Cart"},
  @{id="UC-07"; name="Manage Shopping Cart"; actors="Guest;User"; priority="High"; pre="Cart có ít nhất 1 item"; post="Cart được cập nhật"; flow="1. User vào trang /bag@2. System hiển thị danh sách items: ảnh, tên, color, size, quantity, unit price, subtotal@3. User có thể: tăng/giảm quantity, xóa item@4. System tính lại tổng tiền (subtotal, discount, total)@5. System lưu cart vào localStorage"; altFlow="3a. Giảm quantity xuống 0 -> xóa item khỏi cart@3b. Tăng quantity vượt stock -> giới hạn ở stock tối đa"; category="Shopping Cart"},
  @{id="UC-08"; name="Apply Coupon Code"; actors="Guest;User"; priority="High"; pre="Đang ở trang cart hoặc checkout"; post="Discount được áp dụng (nếu coupon hợp lệ)"; flow="1. User nhập coupon code vào ô 'Promo Code'@2. User bấm 'Apply'@3. System gọi API GET /coupons/validate?code=X&amount=Y@4. System trả về { discountPercent, discountAmount, maxDiscount, finalDiscount }@5. UI hiển thị số tiền giảm giá, tổng mới"; altFlow="3a. Coupon không tồn tại -> 'Invalid code'@3b. Coupon hết hạn -> 'Expired'@3c. Amount < minOrderAmount -> 'Min order not met'"; category="Shopping Cart"},
  @{id="UC-09"; name="Guest Checkout"; actors="Guest"; priority="High"; pre="Cart có ít nhất 1 item"; post="Redirect đến trang thanh toán"; flow="1. User bấm 'Checkout' từ cart@2. System chuyển đến trang /checkout@3. User nhập: firstName, lastName, email, phone, address@4. System validate form@5. User chọn payment method: PayOS hoặc Stripe@6. User bấm 'Place Order'@7. System gọi API POST /payment/checkout/payos hoặc /stripe@8. System kiểm tra stock batch, tạo bill, tạo payment liên kết@9. System redirect đến payment URL (PayOS) hoặc hiển thị Stripe form"; altFlow="7a. Stock batch fail -> hiển thị sản phẩm hết hàng@7b. Coupon đã hết lượt dùng -> thông báo lỗi@7c. API lỗi -> thông báo lỗi server"; category="Checkout & Payment"},
  @{id="UC-10"; name="PayOS Payment Processing"; actors="Guest;User;PayOS Gateway"; priority="High"; pre="Bill đã tạo, payment link pending"; post="Payment hoàn tất hoặc hủy"; flow="1. System tạo PayOS payment link với orderCode, amount, items, returnUrl, cancelUrl@2. PayOS trả về { checkoutUrl, qrCode }@3. System redirect user đến checkoutUrl@4. User thanh toán trên trang PayOS (QR code / bank transfer)@5. PayOS gửi webhook POST /payment/webhook/payos@6. System verify HMAC signature@7. System cập nhật bill status = PAID@8. System giảm stock trong shoesDetail@9. System gửi email xác nhận"; altFlow="4a. User hủy -> redirect về cancelUrl@5a. Webhook timeout -> user query GET /payment/status?orderCode=X@6a. Signature không hợp lệ -> 401"; category="Checkout & Payment"},
  @{id="UC-11"; name="Stripe Payment Processing"; actors="Guest;User;Stripe Gateway"; priority="High"; pre="Bill đã tạo"; post="Payment hoàn tất"; flow="1. System tạo Stripe PaymentIntent với amount, currency, metadata@2. Stripe trả về { clientSecret }@3. Frontend hiển thị Stripe Elements form (thẻ tín dụng)@4. User nhập thông tin thẻ và xác nhận@5. Frontend gọi stripe.confirmCardPayment(clientSecret)@6. Stripe xử lý thanh toán@7. Stripe gửi webhook POST /payment/webhook/stripe@8. System verify với stripe.webhooks.constructEvent()@9. System cập nhật bill status = PAID, giảm stock, gửi email"; altFlow="5a. Thanh toán bị từ chối -> hiển thị lỗi thẻ"; category="Checkout & Payment"},
  @{id="UC-12"; name="Receive Payment Webhook"; actors="PayOS Gateway;Stripe Gateway (External System)"; priority="High"; pre="Payment đã được khởi tạo bởi PayOS/Stripe"; post="Order status được cập nhật"; flow="1. PayOS/Stripe gửi HTTP POST đến webhook endpoint@2. System verify signature (HMAC cho PayOS, Stripe SDK cho Stripe)@3. System kiểm tra idempotency (tránh xử lý trùng)@4. System cập nhật bill.paymentStatus = PAID@5. System gọi processStockAfterPayment để giảm stock@6. System gửi email confirmation@7. System trả về HTTP 200"; altFlow="2a. Signature không hợp lệ -> 401 Unauthorized@3a. Bill đã PAID -> bỏ qua (idempotent)"; category="Checkout & Payment"},
  @{id="UC-13"; name="Track Order by Email + Order Code"; actors="Guest"; priority="High"; pre="Đã đặt hàng (có orderCode và email)"; post="Hiển thị trạng thái đơn hàng"; flow="1. User vào trang /order-tracking@2. User nhập email + orderCode@3. System gọi API GET /payments/status?orderCode=X&email=Y@4. System trả về: orderCode, items, paymentStatus, fulfillmentStatus, carrier, trackingCode, createdAt"; altFlow="3a. Không tìm thấy -> 'Order not found'"; category="Order Tracking"},
  @{id="UC-14"; name="Register New Account"; actors="Guest"; priority="High"; pre="Chưa có tài khoản"; post="Tài khoản được tạo"; flow="1. User vào trang /register@2. User nhập: username, email, password, fullName@3. System validate: username unique, email unique, password strength@4. System hash password (bcrypt) và lưu user vào DB@5. System gửi email xác thực (nếu EMAIL_VERIFICATION_REQUIRED=true)@6. System redirect đến login hoặc auto-login"; altFlow="3a. Username đã tồn tại -> 'Username already exists'@3b. Email đã tồn tại -> 'Email already registered'"; category="Account Management"},
  @{id="UC-15"; name="User Login"; actors="Guest"; priority="High"; pre="Đã có tài khoản"; post="Đăng nhập thành công, nhận JWT token"; flow="1. User vào trang /login@2. User nhập email/username + password@3. System tìm user trong DB@4. System verify password với bcrypt@5. System tạo accessToken (15min) + refreshToken (7d)@6. System trả về { accessToken, refreshToken, user }@7. Frontend lưu token vào localStorage"; altFlow="3a. User không tồn tại -> 'Invalid credentials'@4a. Password sai -> 'Invalid credentials'"; category="Account Management"},
  @{id="UC-16"; name="Manage User Profile"; actors="User"; priority="Medium"; pre="Đã đăng nhập"; post="Profile được cập nhật"; flow="1. User vào trang /profile@2. System hiển thị thông tin: username, email, fullName, phone, avatar@3. User chỉnh sửa fullName, phone@4. System gọi API PUT /auth/profile@5. System cập nhật DB"; altFlow="3a. Phone không hợp lệ -> validation error"; category="Account Management"},
  @{id="UC-17"; name="Manage Addresses"; actors="User"; priority="High"; pre="Đã đăng nhập"; post="Địa chỉ được lưu/cập nhật/xóa"; flow="1. User vào trang /profile/addresses@2. System gọi API GET /auth/addresses@3. System hiển thị danh sách địa chỉ@4. User có thể: thêm, sửa, xóa, đặt làm mặc định@5. System gọi API POST/PUT/DELETE /auth/addresses"; altFlow="5a. Địa chỉ không hợp lệ -> validation error"; category="Account Management"},
  @{id="UC-18"; name="User (Logged-in) Checkout"; actors="User"; priority="High"; pre="Đã đăng nhập, cart có items"; post="Redirect đến thanh toán"; flow="1. User vào checkout@2. System pre-fill thông tin từ profile (name, email, phone)@3. User chọn từ saved addresses hoặc nhập address mới@4. Các bước còn lại giống UC-09 Guest Checkout"; altFlow="3a. Chọn address mặc định -> tự động fill"; category="Checkout & Payment"},
  @{id="UC-19"; name="View Order History"; actors="User"; priority="High"; pre="Đã đăng nhập"; post="Danh sách đơn hàng hiển thị"; flow="1. User vào trang /my-orders@2. System gọi API GET /payments/orders/user/:userId@3. System trả về danh sách bills (orderCode, items, paymentStatus, fulfillmentStatus, total, createdAt)@4. User click vào 1 đơn để xem chi tiết"; altFlow="3a. Chưa có đơn hàng -> empty state"; category="Order Tracking"},
  @{id="UC-20"; name="Write Product Review"; actors="User"; priority="High"; pre="Đã đăng nhập, đã mua sản phẩm"; post="Review được lưu, rating sản phẩm được cập nhật"; flow="1. User vào trang product detail@2. User bấm 'Write Review'@3. User chọn rating (1-5 sao)@4. User nhập comment@5. User upload ảnh (optional, tối đa 5 ảnh)@6. System gọi API POST /reviews@7. System lưu review, cập nhật avg rating của sản phẩm"; altFlow="5a. Ảnh quá lớn (>5MB) -> lỗi@7a. User đã review sản phẩm này -> 409 Conflict"; category="Reviews & Returns"},
  @{id="UC-21"; name="Create Return Request"; actors="User"; priority="High"; pre="Đã đăng nhập, có đơn hàng PAID"; post="Return request PENDING"; flow="1. User vào My Orders@2. User chọn đơn hàng, bấm 'Return/Exchange'@3. User chọn type: RETURN / EXCHANGE / REFUND@4. User chọn sản phẩm, color, size cần trả@5. User nhập lý do@6. User thêm ghi chú (optional)@7. User bấm Submit@8. System gọi API POST /returns@9. System lưu return request (status: PENDING)"; altFlow="8a. Đã có return request cho sản phẩm này -> 409"; category="Reviews & Returns"},
  @{id="UC-22"; name="Track Return Status"; actors="User"; priority="Medium"; pre="Đã tạo return request"; post="Hiển thị trạng thái yêu cầu đổi trả"; flow="1. User vào trang /my-returns@2. System gọi API GET /returns/user/:userId@3. System trả về danh sách return requests (type, reason, status, adminNote, createdAt)@4. User click vào để xem chi tiết"; altFlow="3a. Chưa có return request -> empty state"; category="Reviews & Returns"},
  @{id="UC-23"; name="Manage Wishlist"; actors="User"; priority="Medium"; pre="Đã đăng nhập"; post="Wishlist được cập nhật"; flow="1. User vào trang /wishlist@2. System gọi API GET /wishlist@3. System trả về danh sách sản phẩm yêu thích@4. User có thể xóa khỏi wishlist hoặc thêm vào cart@5. User có thể thêm sản phẩm từ product detail (bấm icon tim)@6. System gọi API POST /wishlist"; altFlow="5a. Sản phẩm đã trong wishlist -> xóa khỏi wishlist (toggle)"; category="Wishlist"},
  @{id="UC-24"; name="Start Chat with Support"; actors="User"; priority="Medium"; pre="Đã đăng nhập"; post="Chat conversation được tạo, tin nhắn được gửi"; flow="1. User bấm vào chat widget (góc phải màn hình)@2. System tạo conversation (nếu chưa có) hoặc mở conversation hiện tại@3. User nhập tin nhắn và gửi@4. System gọi API POST /chat/conversations + POST /chat/convs/:id/messages@5. System tăng unreadForManager counter@6. Tin nhắn hiển thị real-time trên widget"; altFlow="4a. User không đăng nhập -> yêu cầu tên + email"; category="Live Chat"},
  @{id="UC-25"; name="Create New Product"; actors="Admin"; priority="High"; pre="Đã đăng nhập với role admin"; post="Sản phẩm xuất hiện trên store"; flow="1. Admin vào /admin/products@2. Admin bấm 'Add Product'@3. Admin nhập: name, category, productType, collection, base price@4. Admin thêm color variants: colorName, hex code, thumbnail, images, sizes + stock, styleCode, description, materialNote, origin@5. Admin bấm 'Create'@6. System gọi API POST /shoes/product@7. System lưu shoes + shoesDetail vào DB"; altFlow="4c. Stock = 0 cho tất cả sizes -> sản phẩm hidden"; category="Admin - Product Management"},
  @{id="UC-26"; name="Update Product"; actors="Admin"; priority="High"; pre="Sản phẩm tồn tại"; post="Thông tin sản phẩm được cập nhật"; flow="1. Admin vào /admin/products@2. Admin chọn sản phẩm cần sửa@3. Admin chỉnh sửa: giá, mô tả, hình ảnh, stock, colors@4. Admin bấm 'Save'@5. System gọi API PUT/PATCH /shoes/product/:id@6. System cập nhật DB"; altFlow="5a. Dữ liệu không hợp lệ -> 400 Bad Request"; category="Admin - Product Management"},
  @{id="UC-27"; name="Soft Delete Product"; actors="Admin"; priority="Medium"; pre="Sản phẩm tồn tại"; post="Sản phẩm bị ẩn khỏi store (stock = 0)"; flow="1. Admin vào /admin/products@2. Admin chọn sản phẩm@3. Admin bấm 'Delete' (soft delete)@4. System gọi API DELETE /shoes/product/:id@5. System set stock = 0 cho tất cả variants (giữ data)"; altFlow=""; category="Admin - Product Management"},
  @{id="UC-28"; name="Manage Colors & Sizes"; actors="Admin"; priority="High"; pre="Đang tạo/sửa sản phẩm"; post="Color/size variants được cập nhật"; flow="1. Admin chọn color variant, nhập colorName, hex code@2. Admin thêm sizes: size name + stock quantity cho mỗi size@3. Admin có thể thêm/bớt colors và sizes@4. System validate: không trùng colorName trong cùng product@5. System lưu vào shoesDetail.colors[]"; altFlow="4a. Trùng colorName -> lỗi validation"; category="Admin - Product Management"},
  @{id="UC-29"; name="Upload Product Images"; actors="Admin"; priority="Medium"; pre="Đang tạo/sửa sản phẩm"; post="Ảnh được upload lên R2"; flow="1. Admin chọn ảnh từ máy tính@2. System validate: type (jpeg/png/webp), size (max 5MB)@3. System gọi API POST /r2/upload@4. System upload ảnh lên Cloudflare R2@5. System trả về public URL@6. System cập nhật shoesDetail với URLs mới"; altFlow="3a. File không hợp lệ -> validation error@4a. R2 lỗi -> retry hoặc thông báo lỗi"; category="Admin - Product Management"},
  @{id="UC-30"; name="Browse R2 Media"; actors="Admin"; priority="Medium"; pre="Đang tạo/sửa sản phẩm"; post="Hiển thị danh sách ảnh từ R2"; flow="1. Admin mở media browser trong form sản phẩm@2. System gọi API GET /r2/media-folders hoặc list objects@3. System hiển thị danh sách ảnh đã upload@4. Admin chọn ảnh có sẵn thay vì upload mới@5. System thêm URL vào sản phẩm"; altFlow=""; category="Admin - Product Management"},
  @{id="UC-31"; name="Set Discount Price"; actors="Admin"; priority="Medium"; pre="Sản phẩm tồn tại"; post="Giá giảm được áp dụng"; flow="1. Admin chọn sản phẩm@2. Admin nhập discountPrice (nhỏ hơn base price)@3. Admin nhập ngày hết hạn discount (optional)@4. System gọi API PATCH /shoes/product/:id@5. Frontend hiển thị giá gốc gạch ngang + giá giảm"; altFlow="2a. discountPrice > base price -> lỗi"; category="Admin - Product Management"},
  @{id="UC-32"; name="View All Orders"; actors="Admin;Manager"; priority="High"; pre="Đã đăng nhập với role admin/manager"; post="Danh sách tất cả orders hiển thị"; flow="1. Admin vào /admin/purchases@2. System gọi API GET /payments/orders@3. System trả về tất cả bills (paginated)@4. Admin có thể filter/sort theo status, date, amount"; altFlow="3a. Không có đơn hàng -> empty table"; category="Admin - Order & Inventory"},
  @{id="UC-33"; name="Filter/Search Orders"; actors="Admin;Manager"; priority="Medium"; pre="Đang ở trang orders"; post="Kết quả lọc orders hiển thị"; flow="1. Admin nhập từ khóa hoặc chọn filter (status, date range)@2. System gọi API GET /payments/orders?status=CONFIRMED&from=...&to=...@3. System trả về kết quả đã lọc"; altFlow="3a. Không có kết quả -> empty state"; category="Admin - Order & Inventory"},
  @{id="UC-34"; name="View Order Detail"; actors="Admin;Manager"; priority="High"; pre="Đơn hàng tồn tại"; post="Chi tiết đơn hàng hiển thị"; flow="1. Admin click vào 1 order@2. System gọi API GET /payments/orders/:orderCode@3. System trả về: orderCode, items[], paymentDetails, fulfillmentStatus, statusHistory[], customer info, tracking info"; altFlow="2a. Order không tồn tại -> 404"; category="Admin - Order & Inventory"},
  @{id="UC-35"; name="Update Fulfillment Status"; actors="Admin;Manager"; priority="High"; pre="Đơn hàng tồn tại"; post="Fulfillment status được cập nhật"; flow="1. Admin mở chi tiết đơn hàng@2. Admin chọn status mới: CONFIRMED -> PACKING -> SHIPPING -> DELIVERED@3. Nếu chọn SHIPPING: nhập carrier + trackingCode@4. Admin thêm note (optional)@5. System gọi API PATCH /payments/orders/:id/fulfillment@6. System cập nhật fulfillmentStatus, thêm vào statusHistory[]@7. System gửi email thông báo cho khách hàng"; altFlow="5a. Status transition không hợp lệ -> 400"; category="Admin - Order & Inventory"},
  @{id="UC-36"; name="Add Carrier + Tracking"; actors="Admin;Manager"; priority="Medium"; pre="Đơn hàng đang ở status PACKING hoặc SHIPPING"; post="Carrier và tracking code được thêm"; flow="1. Admin nhập tên carrier (VD: Giao Hàng Nhanh, Viettel Post)@2. Admin nhập tracking code@3. System gọi API PATCH /payments/orders/:id/carrier@4. System lưu thông tin, gửi email cho khách"; altFlow=""; category="Admin - Order & Inventory"},
  @{id="UC-37"; name="Add Order Note"; actors="Admin;Manager"; priority="Low"; pre="Đang xem chi tiết đơn hàng"; post="Ghi chú được thêm vào order"; flow="1. Admin nhập note vào ô text@2. Admin bấm 'Add Note'@3. System gọi API POST /payments/orders/:id/notes@4. Note được thêm vào bill.notes[]"; altFlow=""; category="Admin - Order & Inventory"},
  @{id="UC-38"; name="Send Order Status Email"; actors="System (automatic)"; priority="High"; pre="Order status thay đổi"; post="Email được gửi cho khách hàng"; flow="1. Hệ thống phát hiện status thay đổi@2. System xác định template email phù hợp (confirmed, shipped, delivered)@3. System gọi Nodemailer transporter.sendMail()@4. Email được gửi đến email khách hàng@5. System log kết quả"; altFlow="3a. Gửi thất bại -> log lỗi, không block luồng chính"; category="Admin - Order & Inventory"},
  @{id="UC-39"; name="Cancel Order"; actors="Admin;Manager"; priority="Low"; pre="Đơn hàng ở status CONFIRMED hoặc PENDING"; post="Đơn hàng bị hủy"; flow="1. Admin chọn đơn hàng@2. Admin bấm 'Cancel Order'@3. Admin nhập lý do hủy@4. System gọi API POST /payments/orders/:id/cancel@5. System cập nhật status = CANCELLED@6. System hoàn stock (nếu đã trừ)@7. System gửi email thông báo"; altFlow="4a. Đơn hàng đã SHIPPING -> không thể hủy"; category="Admin - Order & Inventory"},
  @{id="UC-40"; name="View Inventory Overview"; actors="Admin;Manager"; priority="High"; pre="Đã đăng nhập với role admin/manager"; post="Hiển thị bảng tồn kho"; flow="1. Admin vào /admin/inventory@2. System gọi API GET /inventory@3. System trả về danh sách products với stock tổng@4. Highlight: low stock (<=5), out of stock (=0)"; altFlow="3a. Lọc theo low-stock only"; category="Admin - Inventory"},
  @{id="UC-41"; name="View Low Stock Alert"; actors="Admin;Manager"; priority="High"; pre="Đang xem inventory"; post="Danh sách sản phẩm low stock hiển thị"; flow="1. System tự động highlight sản phẩm có stock <= 5 (vàng) hoặc = 0 (đỏ)@2. Admin vào tab 'Low Stock'@3. System gọi API GET /inventory?filter=lowStock@4. Hiển thị danh sách cần nhập hàng"; altFlow=""; category="Admin - Inventory"},
  @{id="UC-42"; name="View Stock by Product"; actors="Admin;Manager"; priority="Medium"; pre="Đã chọn 1 sản phẩm"; post="Hiển thị chi tiết stock theo color + size"; flow="1. Admin click vào sản phẩm@2. System gọi API GET /inventory/:productId@3. System trả về colors[] với sizes[] và stock cho mỗi size@4. Hiển thị bảng chi tiết"; altFlow=""; category="Admin - Inventory"},
  @{id="UC-43"; name="Adjust Stock (IN/OUT/ADJUST)"; actors="Admin;Manager"; priority="High"; pre="Đang xem inventory"; post="Stock được cập nhật, stock movement được ghi"; flow="1. Admin chọn sản phẩm, color, size@2. Admin chọn type: IN (nhập hàng) / OUT (xuất hàng) / ADJUST (điều chỉnh)@3. Admin nhập quantity và reason@4. System gọi API POST /inventory/adjust@5. System cập nhật stock trong shoesDetail@6. System tạo stockMovements record"; altFlow="4a. Stock sau điều chỉnh < 0 -> lỗi"; category="Admin - Inventory"},
  @{id="UC-44"; name="View Stock Movements"; actors="Admin;Manager"; priority="Medium"; pre="Đã có stock adjustments"; post="Lịch sử stock movements hiển thị"; flow="1. Admin vào tab 'Stock Movements'@2. System gọi API GET /inventory/movements/:productId@3. System trả về: timestamp, type (IN/OUT/ADJUST), quantity, reason, userId@4. Hiển thị audit trail"; altFlow=""; category="Admin - Inventory"},
  @{id="UC-45"; name="Export Inventory Report"; actors="Admin;Manager"; priority="Low"; pre="Đang xem inventory"; post="File báo cáo được tải xuống"; flow="1. Admin bấm 'Export'@2. System generate CSV/Excel từ dữ liệu inventory@3. System trả về file download"; altFlow=""; category="Admin - Inventory"},
  @{id="UC-46"; name="View Return Requests"; actors="Admin;Manager"; priority="High"; pre="Đã đăng nhập với role admin/manager"; post="Danh sách return requests hiển thị"; flow="1. Admin vào /admin/returns@2. System gọi API GET /returns@3. System trả về: type, orderCode, productId, colorName, size, reason, status, createdAt@4. Admin có thể lọc theo status (PENDING, APPROVED, REJECTED, PROCESSING, COMPLETED)"; altFlow=""; category="Admin - Returns"},
  @{id="UC-47"; name="View Return Request Detail"; actors="Admin;Manager"; priority="High"; pre="Return request tồn tại"; post="Chi tiết return request hiển thị"; flow="1. Admin click vào 1 return request@2. System gọi API GET /returns/:id@3. System trả về: orderCode, user info, product info, type, reason, note, images, status, adminNote"; altFlow=""; category="Admin - Returns"},
  @{id="UC-48"; name="Approve Return Request"; actors="Admin;Manager"; priority="High"; post="Return status = APPROVED"; flow="1. Admin xem chi tiết return request@2. Admin bấm 'Approve'@3. Admin nhập adminNote (optional)@4. System gọi API PATCH /returns/:id/status (body: { status: APPROVED, adminNote })@5. System cập nhật status + adminNote@6. System gửi email thông báo cho user"; altFlow="4a. Status hiện tại không phải PENDING -> lỗi"; category="Admin - Returns"},
  @{id="UC-49"; name="Reject Return Request"; actors="Admin;Manager"; priority="High"; post="Return status = REJECTED"; flow="1. Admin xem chi tiết@2. Admin bấm 'Reject'@3. Admin nhập lý do reject (adminNote required)@4. System gọi API PATCH /returns/:id/status (body: { status: REJECTED, adminNote })@5. System gửi email thông báo"; altFlow=""; category="Admin - Returns"},
  @{id="UC-50"; name="Process Return Request"; actors="Admin;Manager"; priority="Medium"; post="Return status = PROCESSING"; flow="1. Admin chọn return status APPROVED@2. Admin bấm 'Process'@3. System gọi API PATCH /returns/:id/status (body: { status: PROCESSING })@4. System cập nhật status@5. Có thể hoàn stock nếu là RETURN/EXCHANGE"; altFlow=""; category="Admin - Returns"},
  @{id="UC-51"; name="Complete Return Request"; actors="Admin;Manager"; priority="Medium"; post="Return status = COMPLETED"; flow="1. Sau khi xử lý xong (hoàn tiền/đổi hàng)@2. Admin bấm 'Complete'@3. System gọi API PATCH /returns/:id/status (body: { status: COMPLETED })@4. System gửi email cho user@5. Return được đóng"; altFlow=""; category="Admin - Returns"},
  @{id="UC-52"; name="Notify User Return Status"; actors="System (automatic)"; priority="High"; post="Email được gửi cho user"; flow="1. Khi return status thay đổi@2. System xác định template (approved, rejected, processing, completed)@3. System gửi email qua Nodemailer"; altFlow=""; category="Admin - Returns"},
  @{id="UC-53"; name="Create Coupon"; actors="Admin;Manager"; priority="High"; post="Coupon khả dụng cho checkout"; flow="1. Admin vào /admin/coupons@2. Admin bấm 'Create Coupon'@3. Admin nhập: code, description, discountType (PERCENT/FIXED), discountValue, minOrderAmount, maxDiscount, validFrom, validTo, usageLimit@4. System gọi API POST /coupons@5. System lưu coupon"; altFlow="3a. Code đã tồn tại -> 409"; category="Admin - Coupons & Users"},
  @{id="UC-54"; name="Update Coupon"; actors="Admin;Manager"; priority="Medium"; post="Coupon được cập nhật"; flow="1. Admin chọn coupon từ danh sách@2. Admin chỉnh sửa thông tin@3. System gọi API PUT /coupons/:id@4. System validate và cập nhật"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-55"; name="Delete Coupon"; actors="Admin;Manager"; priority="Medium"; post="Coupon bị xóa hoặc vô hiệu"; flow="1. Admin chọn coupon@2. Admin bấm 'Delete'@3. System gọi API DELETE /coupons/:id@4. Coupon bị xóa hoặc set isActive = false"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-56"; name="View Coupons List"; actors="Admin;Manager"; priority="Medium"; post="Danh sách coupons hiển thị"; flow="1. Admin vào /admin/coupons@2. System gọi API GET /coupons@3. System trả về: code, discount, validFrom, validTo, isActive, usageCount"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-57"; name="View Users List"; actors="Admin"; priority="High"; post="Danh sách users hiển thị"; flow="1. Admin vào /admin/users@2. System gọi API GET /auth/users@3. System trả về: username, email, fullName, role, createdAt, isActive"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-58"; name="View User Detail"; actors="Admin"; priority="Medium"; post="Chi tiết user hiển thị"; flow="1. Admin click vào user@2. System gọi API GET /auth/users/:userId@3. System trả về: username, email, fullName, phone, role, addresses, createdAt, orderCount"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-59"; name="Change User Role"; actors="Admin"; priority="High"; pre="Target user không phải chính mình"; post="Role của user được thay đổi"; flow="1. Admin chọn user@2. Admin chọn role mới từ dropdown@3. System gọi API PATCH /auth/users/:userId/role@4. System cập nhật role trong DB"; altFlow="2a. Admin cố gắng đổi role chính mình -> lỗi"; category="Admin - Coupons & Users"},
  @{id="UC-60"; name="Disable User"; actors="Admin"; priority="Medium"; post="User bị vô hiệu hóa"; flow="1. Admin chọn user@2. Admin bấm 'Disable'@3. System gọi API PATCH /auth/users/:userId/disable@4. User bị set isActive = false, không thể login"; altFlow=""; category="Admin - Coupons & Users"},
  @{id="UC-61"; name="View Dashboard Overview"; actors="Admin;Manager"; priority="High"; post="Dashboard hiển thị metrics tổng quan"; flow="1. Admin vào /admin/dashboard@2. System gọi API GET /analytics/dashboard@3. System trả về: totalRevenue, totalOrders, totalProducts, totalUsers, recentOrders[], topProducts[]@4. Frontend hiển thị summary cards + charts"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-62"; name="View Revenue Stats"; actors="Admin;Manager"; priority="High"; post="Biểu đồ doanh thu hiển thị"; flow="1. Admin xem revenue section trên dashboard@2. System gọi API GET /analytics/revenue?from=...&to=...@3. System trả về: revenue by day/week/month@4. Hiển thị line chart / bar chart"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-63"; name="View Order Stats"; actors="Admin;Manager"; priority="High"; post="Thống kê đơn hàng hiển thị"; flow="1. Admin xem order stats section@2. System gọi API GET /analytics/orders?from=...&to=...@3. System trả về: totalOrders, ordersByStatus, ordersByDay@4. Hiển thị pie chart + line chart"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-64"; name="View Product Stats"; actors="Admin;Manager"; priority="Medium"; post="Thống kê sản phẩm hiển thị"; flow="1. System trả về top selling products, products by category@2. Hiển thị bar chart top 10 sản phẩm bán chạy"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-65"; name="View User Stats"; actors="Admin"; priority="Medium"; post="Thống kê user hiển thị"; flow="1. System trả về: totalUsers, newUsers by day/week, user roles breakdown@2. Hiển thị line chart + pie chart"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-66"; name="Filter by Date Range"; actors="Admin;Manager"; priority="Medium"; post="Dữ liệu được lọc theo khoảng thời gian"; flow="1. Admin chọn date range (today, 7 days, 30 days, custom)@2. System gọi API với query params from/to@3. Tất cả charts cập nhật theo range đã chọn"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-67"; name="Export Analytics Report"; actors="Admin"; priority="Low"; post="File báo cáo được tải xuống"; flow="1. Admin bấm 'Export'@2. System generate PDF/CSV report@3. System trả về file download"; altFlow=""; category="Admin - Analytics"},
  @{id="UC-68"; name="Open Chat Widget (Guest)"; actors="Guest"; priority="Medium"; post="Chat widget mở, sẵn sàng gửi tin nhắn"; flow="1. Guest bấm vào chat icon góc phải@2. System hiển thị form: nhập name + email@3. Guest nhập thông tin@4. System tạo conversation@5. Guest có thể gửi tin nhắn đầu tiên"; altFlow=""; category="Live Chat"},
  @{id="UC-69"; name="Send Chat Message"; actors="Guest;User"; priority="Medium"; post="Tin nhắn được gửi"; flow="1. User/guest nhập tin nhắn vào chat widget@2. User bấm Send@3. System gọi API POST /chat/convs/:id/messages@4. System push message vào messages[]@5. System tăng unreadForManager@6. Tin nhắn hiển thị trong chat widget"; altFlow=""; category="Live Chat"},
  @{id="UC-70"; name="Receive Chat Reply"; actors="Guest;User"; priority="Medium"; post="User nhận được reply từ admin"; flow="1. User refresh hoặc poll@2. System gọi API GET /chat/convs/:id@3. System trả về messages[] mới nhất@4. User thấy admin reply trong widget"; altFlow=""; category="Live Chat"},
  @{id="UC-71"; name="View Open Conversations"; actors="Admin;Manager"; priority="High"; post="Danh sách conversations hiển thị"; flow="1. Admin vào /admin/chat@2. System gọi API GET /chat/conversations?status=open@3. System trả về danh sách: convId, userName, lastMessage, unreadForManager, updatedAt@4. Highlight conversations có unread > 0"; altFlow=""; category="Admin - Chat"},
  @{id="UC-72"; name="Open Conversation (Admin)"; actors="Admin;Manager"; priority="High"; post="Lịch sử chat hiển thị"; flow="1. Admin click vào conversation@2. System gọi API GET /chat/convs/:id@3. System trả về messages[]@4. Admin đọc tin nhắn@5. System đánh dấu đã đọc (PATCH /chat/convs/:id/read)"; altFlow=""; category="Admin - Chat"},
  @{id="UC-73"; name="Reply to Customer Chat"; actors="Admin;Manager"; priority="High"; post="Tin nhắn reply được gửi"; flow="1. Admin nhập reply@2. Admin bấm Send@3. System gọi API POST /chat/convs/:id/messages (body: { senderType: 'manager', text })@4. System push message, tăng unread cho user@5. Customer thấy reply trong widget"; altFlow=""; category="Admin - Chat"},
  @{id="UC-74"; name="Mark Conversation Read"; actors="Admin;Manager"; priority="Low"; post="unreadForManager = 0"; flow="1. Admin mở conversation@2. System tự động gọi PATCH /chat/convs/:id/read (target: 'manager')@3. unreadForManager reset về 0"; altFlow=""; category="Admin - Chat"},
  @{id="UC-75"; name="Close Conversation"; actors="Admin;Manager"; priority="Low"; post="Conversation status = CLOSED"; flow="1. Admin bấm 'Close Chat'@2. System gọi API PATCH /chat/convs/:id/close@3. System set status = CLOSED@4. Conversation không còn xuất hiện trong danh sách mở"; altFlow=""; category="Admin - Chat"}
)

foreach ($uc in $ucs) {
  $mainFlow = $uc.flow -split '@' -join "`n      "
  $altFlow = if ($uc.altFlow -ne "") { ($uc.altFlow -split '@' -join "`n      ") } else { "" }
  $actors = $uc.actors -split ';' -join "`n    </Actor>`n    <Actor>"
  $category = $uc.category

  $xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<UseCase id="$($uc.id)" name="$($uc.name)" category="$category">
  <Actors>
    <Actor>$actors</Actor>
  </Actors>
  <Priority>$($uc.priority)</Priority>
  <Precondition>
    $($uc.pre)
  </Precondition>
  <Postcondition>
    $($uc.post)
  </Postcondition>
  <MainFlow>
    $mainFlow
  </MainFlow>
  <AlternativeFlows>
    $altFlow
  </AlternativeFlows>
</UseCase>
"@

  $fileName = "$BASE\$($uc.id)-$($uc.name -replace '[\\/:*?"<>|]', '-').xml"
  $xml | Set-Content -LiteralPath $fileName -Encoding UTF8
}

Write-Host "Generated $($ucs.Count) use case XML files in $BASE"
