// UC-13 to UC-75 source data; scripts/generate-uc-uml.js appends UC-76.
const gen = require("./uc-gen");
const { ucs, esc, BASE, fs, path } = gen;

// Part 2: UC-13 to UC-39 (Order Tracking, Account, Reviews, Returns, Wishlist, Chat, Admin Product/Order)
ucs.push(
{id:"UC-13",name:"Track Order by Email + Order Code",actors:["Guest"],pri:"High",
pre:"Đã đặt hàng (có orderCode và email)",post:"Hiển thị trạng thái đơn hàng",
mf:["User vào trang /order-tracking","User nhập email + orderCode","System gọi API GET /payments/status?orderCode=X&email=Y","System trả về: orderCode, items, paymentStatus, fulfillmentStatus, carrier, trackingCode, createdAt"],
af:["Không tìm thấy -> Order not found"],cat:"Order Tracking"},
{id:"UC-14",name:"Register New Account",actors:["Guest"],pri:"High",
pre:"Chưa có tài khoản",post:"Tài khoản được tạo",
mf:["User vào trang /register","User nhập: username, email, password, fullName","System validate: username unique, email unique, password strength","System hash password (bcrypt) và lưu user vào DB","System gửi email xác thực (nếu EMAIL_VERIFICATION_REQUIRED=true)","System redirect đến login hoặc auto-login"],
af:["Username đã tồn tại -> Username already exists","Email đã tồn tại -> Email already registered"],cat:"Account Management"},
{id:"UC-15",name:"User Login",actors:["Guest"],pri:"High",
pre:"Đã có tài khoản",post:"Đăng nhập thành công, nhận JWT token",
mf:["User vào trang /login","User nhập email/username + password","System tìm user trong DB","System verify password với bcrypt","System tạo accessToken (15min) + refreshToken (7d)","System trả về { accessToken, refreshToken, user }","Frontend lưu token vào localStorage"],
af:["User không tồn tại -> Invalid credentials","Password sai -> Invalid credentials"],cat:"Account Management"},
{id:"UC-16",name:"Manage User Profile",actors:["User"],pri:"Medium",
pre:"Đã đăng nhập",post:"Profile được cập nhật",
mf:["User vào trang /profile","System hiển thị thông tin: username, email, fullName, phone, avatar","User chỉnh sửa fullName, phone","System gọi API PUT /auth/profile","System cập nhật DB"],
af:["Phone không hợp lệ -> validation error"],cat:"Account Management"},
{id:"UC-17",name:"Manage Addresses",actors:["User"],pri:"High",
pre:"Đã đăng nhập",post:"Địa chỉ được lưu/cập nhật/xóa",
mf:["User vào trang /profile/addresses","System gọi API GET /auth/addresses","System hiển thị danh sách địa chỉ","User có thể: thêm, sửa, xóa, đặt làm mặc định","System gọi API POST/PUT/DELETE /auth/addresses"],
af:["Địa chỉ không hợp lệ -> validation error"],cat:"Account Management"},
{id:"UC-18",name:"User (Logged-in) Checkout",actors:["User"],pri:"High",
pre:"Đã đăng nhập, cart có items",post:"Redirect đến thanh toán",
mf:["User vào checkout","System pre-fill thông tin từ profile (name, email, phone)","User chọn từ saved addresses hoặc nhập address mới","Các bước còn lại giống UC-09 Guest Checkout"],
af:["Chọn address mặc định -> tự động fill"],cat:"Checkout & Payment"},
{id:"UC-19",name:"View Order History",actors:["User"],pri:"High",
pre:"Đã đăng nhập",post:"Danh sách đơn hàng hiển thị",
mf:["User vào trang /my-orders","System gọi API GET /payments/orders/user/:userId","System trả về danh sách bills (orderCode, items, paymentStatus, fulfillmentStatus, total, createdAt)","User click vào 1 đơn để xem chi tiết"],
af:["Chưa có đơn hàng -> empty state"],cat:"Order Tracking"},
{id:"UC-20",name:"Write Product Review",actors:["User"],pri:"High",
pre:"Đã đăng nhập, đã mua sản phẩm",post:"Review được lưu, rating sản phẩm được cập nhật",
mf:["User vào trang product detail","User bấm Write Review","User chọn rating (1-5 sao)","User nhập comment","User upload ảnh (optional, tối đa 5 ảnh)","System gọi API POST /reviews","System lưu review, cập nhật avg rating của sản phẩm"],
af:["Ảnh quá lớn (>5MB) -> lỗi","User đã review sản phẩm này -> 409 Conflict"],cat:"Reviews & Returns"},
{id:"UC-21",name:"Create Return Request",actors:["User"],pri:"High",
pre:"Đã đăng nhập, có đơn hàng PAID",post:"Return request PENDING",
mf:["User vào My Orders","User chọn đơn hàng, bấm Return/Exchange","User chọn type: RETURN / EXCHANGE / REFUND","User chọn sản phẩm, color, size cần trả","User nhập lý do","User thêm ghi chú (optional)","User bấm Submit","System gọi API POST /returns","System lưu return request (status: PENDING)"],
af:["Đã có return request cho sản phẩm này -> 409"],cat:"Reviews & Returns"},
{id:"UC-22",name:"Track Return Status",actors:["User"],pri:"Medium",
pre:"Đã tạo return request",post:"Hiển thị trạng thái yêu cầu đổi trả",
mf:["User vào trang /my-returns","System gọi API GET /returns/user/:userId","System trả về danh sách return requests (type, reason, status, adminNote, createdAt)","User click vào để xem chi tiết"],
af:["Chưa có return request -> empty state"],cat:"Reviews & Returns"},
{id:"UC-23",name:"Manage Wishlist",actors:["User"],pri:"Medium",
pre:"Đã đăng nhập",post:"Wishlist được cập nhật",
mf:["User vào trang /wishlist","System gọi API GET /wishlist","System trả về danh sách sản phẩm yêu thích","User có thể xóa khỏi wishlist hoặc thêm vào cart","User có thể thêm sản phẩm từ product detail (bấm icon tim)","System gọi API POST /wishlist"],
af:["Sản phẩm đã trong wishlist -> xóa khỏi wishlist (toggle)"],cat:"Wishlist"},
{id:"UC-24",name:"Start Chat with Support",actors:["User"],pri:"Medium",
pre:"Đã đăng nhập",post:"Chat conversation được tạo, tin nhắn được gửi",
mf:["User bấm vào chat widget (góc phải màn hình)","System tạo conversation (nếu chưa có) hoặc mở conversation hiện tại","User nhập tin nhắn và gửi","System gọi API POST /chat/conversations + POST /chat/convs/:id/messages","System tăng unreadForManager counter","Tin nhắn hiển thị real-time trên widget"],
af:["User không đăng nhập -> yêu cầu tên + email"],cat:"Live Chat"},
{id:"UC-25",name:"Create New Product",actors:["Admin"],pri:"High",
pre:"Đã đăng nhập với role admin",post:"Sản phẩm xuất hiện trên store",
mf:["Admin vào /admin/products","Admin bấm Add Product","Admin nhập: name, category, productType, collection, base price","Admin thêm color variants: colorName, hex code, thumbnail, images, sizes + stock, styleCode, description, materialNote, origin","Admin bấm Create","System gọi API POST /shoes/product","System lưu shoes + shoesDetail vào DB"],
af:["Stock = 0 cho tất cả sizes -> sản phẩm hidden"],cat:"Admin - Product Management"},
{id:"UC-26",name:"Update Product",actors:["Admin"],pri:"High",
pre:"Sản phẩm tồn tại",post:"Thông tin sản phẩm được cập nhật",
mf:["Admin vào /admin/products","Admin chọn sản phẩm cần sửa","Admin chỉnh sửa: giá, mô tả, hình ảnh, stock, colors","Admin bấm Save","System gọi API PUT/PATCH /shoes/product/:id","System cập nhật DB"],
af:["Dữ liệu không hợp lệ -> 400 Bad Request"],cat:"Admin - Product Management"},
{id:"UC-27",name:"Soft Delete Product",actors:["Admin"],pri:"Medium",
pre:"Sản phẩm tồn tại",post:"Sản phẩm bị ẩn khỏi store (stock = 0)",
mf:["Admin vào /admin/products","Admin chọn sản phẩm","Admin bấm Delete (soft delete)","System gọi API DELETE /shoes/product/:id","System set stock = 0 cho tất cả variants (giữ data)"],
af:[],cat:"Admin - Product Management"},
{id:"UC-28",name:"Manage Colors & Sizes",actors:["Admin"],pri:"High",
pre:"Đang tạo/sửa sản phẩm",post:"Color/size variants được cập nhật",
mf:["Admin chọn color variant, nhập colorName, hex code","Admin thêm sizes: size name + stock quantity cho mỗi size","Admin có thể thêm/bớt colors và sizes","System validate: không trùng colorName trong cùng product","System lưu vào shoesDetail.colors[]"],
af:["Trùng colorName -> lỗi validation"],cat:"Admin - Product Management"},
{id:"UC-29",name:"Upload Product Images",actors:["Admin"],pri:"Medium",
pre:"Đang tạo/sửa sản phẩm",post:"Ảnh được upload lên R2",
mf:["Admin chọn ảnh từ máy tính","System validate: type (jpeg/png/webp), size (max 5MB)","System gọi API POST /r2/upload","System upload ảnh lên Cloudflare R2","System trả về public URL","System cập nhật shoesDetail với URLs mới"],
af:["File không hợp lệ -> validation error","R2 lỗi -> retry hoặc thông báo lỗi"],cat:"Admin - Product Management"},
{id:"UC-30",name:"Browse R2 Media",actors:["Admin"],pri:"Medium",
pre:"Đang tạo/sửa sản phẩm",post:"Hiển thị danh sách ảnh từ R2",
mf:["Admin mở media browser trong form sản phẩm","System gọi API GET /r2/media-folders hoặc list objects","System hiển thị danh sách ảnh đã upload","Admin chọn ảnh có sẵn thay vì upload mới","System thêm URL vào sản phẩm"],
af:[],cat:"Admin - Product Management"},
{id:"UC-31",name:"Set Discount Price",actors:["Admin"],pri:"Medium",
pre:"Sản phẩm tồn tại",post:"Giá giảm được áp dụng",
mf:["Admin chọn sản phẩm","Admin nhập discountPrice (nhỏ hơn base price)","Admin nhập ngày hết hạn discount (optional)","System gọi API PATCH /shoes/product/:id","Frontend hiển thị giá gốc gạch ngang + giá giảm"],
af:["discountPrice > base price -> lỗi"],cat:"Admin - Product Management"},
{id:"UC-32",name:"View All Orders",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Danh sách tất cả orders hiển thị",
mf:["Admin vào /admin/purchases","System gọi API GET /payments/orders","System trả về tất cả bills (paginated)","Admin có thể filter/sort theo status, date, amount"],
af:["Không có đơn hàng -> empty table"],cat:"Admin - Order & Inventory"},
{id:"UC-33",name:"Filter/Search Orders",actors:["Admin","Manager"],pri:"Medium",
pre:"Đang ở trang orders",post:"Kết quả lọc orders hiển thị",
mf:["Admin nhập từ khóa hoặc chọn filter (status, date range)","System gọi API GET /payments/orders?status=CONFIRMED&from=...&to=...","System trả về kết quả đã lọc"],
af:["Không có kết quả -> empty state"],cat:"Admin - Order & Inventory"},
{id:"UC-34",name:"View Order Detail",actors:["Admin","Manager"],pri:"High",
pre:"Đơn hàng tồn tại",post:"Chi tiết đơn hàng hiển thị",
mf:["Admin click vào 1 order","System gọi API GET /payments/orders/:orderCode","System trả về: orderCode, items[], paymentDetails, fulfillmentStatus, statusHistory[], customer info, tracking info"],
af:["Order không tồn tại -> 404"],cat:"Admin - Order & Inventory"},
{id:"UC-35",name:"Update Fulfillment Status",actors:["Admin","Manager"],pri:"High",
pre:"Đơn hàng tồn tại",post:"Fulfillment status được cập nhật",
mf:["Admin mở chi tiết đơn hàng","Admin chọn status mới: CONFIRMED -> PACKING -> SHIPPING -> DELIVERED","Nếu chọn SHIPPING: nhập carrier + trackingCode","Admin thêm note (optional)","System gọi API PATCH /payments/orders/:id/fulfillment","System cập nhật fulfillmentStatus, thêm vào statusHistory[]","System gửi email thông báo cho khách hàng"],
af:["Status transition không hợp lệ -> 400"],cat:"Admin - Order & Inventory"},
{id:"UC-36",name:"Add Carrier + Tracking",actors:["Admin","Manager"],pri:"Medium",
pre:"Đơn hàng đang ở status PACKING hoặc SHIPPING",post:"Carrier và tracking code được thêm",
mf:["Admin nhập tên carrier (VD: Giao Hàng Nhanh, Viettel Post)","Admin nhập tracking code","System gọi API PATCH /payments/orders/:id/carrier","System lưu thông tin, gửi email cho khách"],
af:[],cat:"Admin - Order & Inventory"},
{id:"UC-37",name:"Add Order Note",actors:["Admin","Manager"],pri:"Low",
pre:"Đang xem chi tiết đơn hàng",post:"Ghi chú được thêm vào order",
mf:["Admin nhập note vào ô text","Admin bấm Add Note","System gọi API POST /payments/orders/:id/notes","Note được thêm vào bill.notes[]"],
af:[],cat:"Admin - Order & Inventory"},
{id:"UC-38",name:"Send Order Status Email",actors:["System"],pri:"High",
pre:"Order status thay đổi",post:"Email được gửi cho khách hàng",
mf:["Hệ thống phát hiện status thay đổi","System xác định template email phù hợp (confirmed, shipped, delivered)","System gọi Nodemailer transporter.sendMail()","Email được gửi đến email khách hàng","System log kết quả"],
af:["Gửi thất bại -> log lỗi, không block luồng chính"],cat:"Admin - Order & Inventory"},
{id:"UC-39",name:"Cancel Order",actors:["Admin","Manager"],pri:"Low",
pre:"Đơn hàng ở status CONFIRMED hoặc PENDING",post:"Đơn hàng bị hủy",
mf:["Admin chọn đơn hàng","Admin bấm Cancel Order","Admin nhập lý do hủy","System gọi API POST /payments/orders/:id/cancel","System cập nhật status = CANCELLED","System hoàn stock (nếu đã trừ)","System gửi email thông báo"],
af:["Đơn hàng đã SHIPPING -> không thể hủy"],cat:"Admin - Order & Inventory"}
);
