// Legacy UC-01..UC-75 source data + generator logic; scripts/generate-uc-uml.js appends UC-76.
const gen = require("./uc-gen");
require("./uc-gen-2"); // pushes UC-13..UC-39 to shared ucs array
const { esc, BASE, fs, path } = gen;
const ucs = gen.ucs;

// Part 3: UC-40 to UC-75 (Inventory, Returns, Coupons, Users, Analytics, Chat)
ucs.push(
{id:"UC-40",name:"View Inventory Overview",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Hiển thị bảng tồn kho",
mf:["Admin vào /admin/inventory","System gọi API GET /inventory","System trả về danh sách products với stock tổng","Highlight: low stock (<=5), out of stock (=0)"],
af:["Lọc theo low-stock only"],cat:"Admin - Inventory"},
{id:"UC-41",name:"View Low Stock Alert",actors:["Admin","Manager"],pri:"High",
pre:"Đang xem inventory",post:"Danh sách sản phẩm low stock hiển thị",
mf:["System tự động highlight sản phẩm có stock <= 5 (vàng) hoặc = 0 (đỏ)","Admin vào tab Low Stock","System gọi API GET /inventory?filter=lowStock","Hiển thị danh sách cần nhập hàng"],
af:[],cat:"Admin - Inventory"},
{id:"UC-42",name:"View Stock by Product",actors:["Admin","Manager"],pri:"Medium",
pre:"Đã chọn 1 sản phẩm",post:"Hiển thị chi tiết stock theo color + size",
mf:["Admin click vào sản phẩm","System gọi API GET /inventory/:productId","System trả về colors[] với sizes[] và stock cho mỗi size","Hiển thị bảng chi tiết"],
af:[],cat:"Admin - Inventory"},
{id:"UC-43",name:"Adjust Stock (IN/OUT/ADJUST)",actors:["Admin","Manager"],pri:"High",
pre:"Đang xem inventory",post:"Stock được cập nhật, stock movement được ghi",
mf:["Admin chọn sản phẩm, color, size","Admin chọn type: IN (nhập hàng) / OUT (xuất hàng) / ADJUST (điều chỉnh)","Admin nhập quantity và reason","System gọi API POST /inventory/adjust","System cập nhật stock trong shoesDetail","System tạo stockMovements record"],
af:["Stock sau điều chỉnh < 0 -> lỗi"],cat:"Admin - Inventory"},
{id:"UC-44",name:"View Stock Movements",actors:["Admin","Manager"],pri:"Medium",
pre:"Đã có stock adjustments",post:"Lịch sử stock movements hiển thị",
mf:["Admin vào tab Stock Movements","System gọi API GET /inventory/movements/:productId","System trả về: timestamp, type (IN/OUT/ADJUST), quantity, reason, userId","Hiển thị audit trail"],
af:[],cat:"Admin - Inventory"},
{id:"UC-45",name:"Export Inventory Report",actors:["Admin","Manager"],pri:"Low",
pre:"Đang xem inventory",post:"File báo cáo được tải xuống",
mf:["Admin bấm Export","System generate CSV/Excel từ dữ liệu inventory","System trả về file download"],
af:[],cat:"Admin - Inventory"},
{id:"UC-46",name:"View Return Requests",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Danh sách return requests hiển thị",
mf:["Admin vào /admin/returns","System gọi API GET /returns","System trả về: type, orderCode, productId, colorName, size, reason, status, createdAt","Admin có thể lọc theo status (PENDING, APPROVED, REJECTED, PROCESSING, COMPLETED)"],
af:[],cat:"Admin - Returns"},
{id:"UC-47",name:"View Return Request Detail",actors:["Admin","Manager"],pri:"High",
pre:"Return request tồn tại",post:"Chi tiết return request hiển thị",
mf:["Admin click vào 1 return request","System gọi API GET /returns/:id","System trả về: orderCode, user info, product info, type, reason, note, images, status, adminNote"],
af:[],cat:"Admin - Returns"},
{id:"UC-48",name:"Approve Return Request",actors:["Admin","Manager"],pri:"High",
pre:"Return request đang ở status PENDING",post:"Return status = APPROVED",
mf:["Admin xem chi tiết return request","Admin bấm Approve","Admin nhập adminNote (optional)","System gọi API PATCH /returns/:id/status { status: APPROVED, adminNote }","System cập nhật status + adminNote","System gửi email thông báo cho user"],
af:["Status hiện tại không phải PENDING -> lỗi"],cat:"Admin - Returns"},
{id:"UC-49",name:"Reject Return Request",actors:["Admin","Manager"],pri:"High",
pre:"Return request đang ở status PENDING",post:"Return status = REJECTED",
mf:["Admin xem chi tiết","Admin bấm Reject","Admin nhập lý do reject (adminNote required)","System gọi API PATCH /returns/:id/status { status: REJECTED, adminNote }","System gửi email thông báo"],
af:[],cat:"Admin - Returns"},
{id:"UC-50",name:"Process Return Request",actors:["Admin","Manager"],pri:"Medium",
pre:"Return status = APPROVED",post:"Return status = PROCESSING",
mf:["Admin chọn return status APPROVED","Admin bấm Process","System gọi API PATCH /returns/:id/status { status: PROCESSING }","System cập nhật status","Có thể hoàn stock nếu là RETURN/EXCHANGE"],
af:[],cat:"Admin - Returns"},
{id:"UC-51",name:"Complete Return Request",actors:["Admin","Manager"],pri:"Medium",
pre:"Return status = PROCESSING",post:"Return status = COMPLETED",
mf:["Sau khi xử lý xong (hoàn tiền/đổi hàng)","Admin bấm Complete","System gọi API PATCH /returns/:id/status { status: COMPLETED }","System gửi email cho user","Return được đóng"],
af:[],cat:"Admin - Returns"},
{id:"UC-52",name:"Notify User Return Status",actors:["System"],pri:"High",
pre:"Return status thay đổi",post:"Email được gửi cho user",
mf:["Khi return status thay đổi","System xác định template (approved, rejected, processing, completed)","System gửi email qua Nodemailer"],
af:[],cat:"Admin - Returns"},
{id:"UC-53",name:"Create Coupon",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Coupon khả dụng cho checkout",
mf:["Admin vào /admin/coupons","Admin bấm Create Coupon","Admin nhập: code, description, discountType (PERCENT/FIXED), discountValue, minOrderAmount, maxDiscount, validFrom, validTo, usageLimit","System gọi API POST /coupons","System lưu coupon"],
af:["Code đã tồn tại -> 409"],cat:"Admin - Coupons & Users"},
{id:"UC-54",name:"Update Coupon",actors:["Admin","Manager"],pri:"Medium",
pre:"Coupon tồn tại",post:"Coupon được cập nhật",
mf:["Admin chọn coupon từ danh sách","Admin chỉnh sửa thông tin","System gọi API PUT /coupons/:id","System validate và cập nhật"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-55",name:"Delete Coupon",actors:["Admin","Manager"],pri:"Medium",
pre:"Coupon tồn tại",post:"Coupon bị xóa hoặc vô hiệu",
mf:["Admin chọn coupon","Admin bấm Delete","System gọi API DELETE /coupons/:id","Coupon bị xóa hoặc set isActive = false"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-56",name:"View Coupons List",actors:["Admin","Manager"],pri:"Medium",
pre:"Đã đăng nhập với role admin/manager",post:"Danh sách coupons hiển thị",
mf:["Admin vào /admin/coupons","System gọi API GET /coupons","System trả về: code, discount, validFrom, validTo, isActive, usageCount"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-57",name:"View Users List",actors:["Admin"],pri:"High",
pre:"Đã đăng nhập với role admin",post:"Danh sách users hiển thị",
mf:["Admin vào /admin/users","System gọi API GET /auth/users","System trả về: username, email, fullName, role, createdAt, isActive"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-58",name:"View User Detail",actors:["Admin"],pri:"Medium",
pre:"User tồn tại",post:"Chi tiết user hiển thị",
mf:["Admin click vào user","System gọi API GET /auth/users/:userId","System trả về: username, email, fullName, phone, role, addresses, createdAt, orderCount"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-59",name:"Change User Role",actors:["Admin"],pri:"High",
pre:"Target user không phải chính mình",post:"Role của user được thay đổi",
mf:["Admin chọn user","Admin chọn role mới từ dropdown","System gọi API PATCH /auth/users/:userId/role","System cập nhật role trong DB"],
af:["Admin cố gắng đổi role chính mình -> lỗi"],cat:"Admin - Coupons & Users"},
{id:"UC-60",name:"Disable User",actors:["Admin"],pri:"Medium",
pre:"User tồn tại",post:"User bị vô hiệu hóa, không thể login",
mf:["Admin chọn user","Admin bấm Disable","System gọi API PATCH /auth/users/:userId/disable","User bị set isActive = false"],
af:[],cat:"Admin - Coupons & Users"},
{id:"UC-61",name:"View Dashboard Overview",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Dashboard hiển thị metrics tổng quan",
mf:["Admin vào /admin/dashboard","System gọi API GET /analytics/dashboard","System trả về: totalRevenue, totalOrders, totalProducts, totalUsers, recentOrders[], topProducts[]","Frontend hiển thị summary cards + charts"],
af:[],cat:"Admin - Analytics"},
{id:"UC-62",name:"View Revenue Stats",actors:["Admin","Manager"],pri:"High",
pre:"Đang ở dashboard",post:"Biểu đồ doanh thu hiển thị",
mf:["Admin xem revenue section trên dashboard","System gọi API GET /analytics/revenue?from=...&to=...","System trả về: revenue by day/week/month","Hiển thị line chart / bar chart"],
af:[],cat:"Admin - Analytics"},
{id:"UC-63",name:"View Order Stats",actors:["Admin","Manager"],pri:"High",
pre:"Đang ở dashboard",post:"Thống kê đơn hàng hiển thị",
mf:["Admin xem order stats section","System gọi API GET /analytics/orders?from=...&to=...","System trả về: totalOrders, ordersByStatus, ordersByDay","Hiển thị pie chart + line chart"],
af:[],cat:"Admin - Analytics"},
{id:"UC-64",name:"View Product Stats",actors:["Admin","Manager"],pri:"Medium",
pre:"Đang ở dashboard",post:"Thống kê sản phẩm hiển thị",
mf:["System trả về top selling products, products by category","Hiển thị bar chart top 10 sản phẩm bán chạy"],
af:[],cat:"Admin - Analytics"},
{id:"UC-65",name:"View User Stats",actors:["Admin"],pri:"Medium",
pre:"Đang ở dashboard",post:"Thống kê user hiển thị",
mf:["System trả về: totalUsers, newUsers by day/week, user roles breakdown","Hiển thị line chart + pie chart"],
af:[],cat:"Admin - Analytics"},
{id:"UC-66",name:"Filter by Date Range",actors:["Admin","Manager"],pri:"Medium",
pre:"Đang ở dashboard",post:"Dữ liệu được lọc theo khoảng thời gian",
mf:["Admin chọn date range (today, 7 days, 30 days, custom)","System gọi API với query params from/to","Tất cả charts cập nhật theo range đã chọn"],
af:[],cat:"Admin - Analytics"},
{id:"UC-67",name:"Export Analytics Report",actors:["Admin"],pri:"Low",
pre:"Đang ở dashboard",post:"File báo cáo được tải xuống",
mf:["Admin bấm Export","System generate PDF/CSV report","System trả về file download"],
af:[],cat:"Admin - Analytics"},
{id:"UC-68",name:"Open Chat Widget (Guest)",actors:["Guest"],pri:"Medium",
pre:"Chưa đăng nhập, mở chat widget",post:"Chat widget mở, sẵn sàng gửi tin nhắn",
mf:["Guest bấm vào chat icon góc phải","System hiển thị form: nhập name + email","Guest nhập thông tin","System tạo conversation","Guest có thể gửi tin nhắn đầu tiên"],
af:[],cat:"Live Chat"},
{id:"UC-69",name:"Send Chat Message",actors:["Guest","User"],pri:"Medium",
pre:"Chat conversation đang mở",post:"Tin nhắn được gửi",
mf:["User/guest nhập tin nhắn vào chat widget","User bấm Send","System gọi API POST /chat/convs/:id/messages","System push message vào messages[]","System tăng unreadForManager","Tin nhắn hiển thị trong chat widget"],
af:[],cat:"Live Chat"},
{id:"UC-70",name:"Receive Chat Reply",actors:["Guest","User"],pri:"Medium",
pre:"Đã gửi tin nhắn",post:"User nhận được reply từ admin",
mf:["User refresh hoặc poll","System gọi API GET /chat/convs/:id","System trả về messages[] mới nhất","User thấy admin reply trong widget"],
af:[],cat:"Live Chat"},
{id:"UC-71",name:"View Open Conversations",actors:["Admin","Manager"],pri:"High",
pre:"Đã đăng nhập với role admin/manager",post:"Danh sách conversations hiển thị",
mf:["Admin vào /admin/chat","System gọi API GET /chat/conversations?status=open","System trả về danh sách: convId, userName, lastMessage, unreadForManager, updatedAt","Highlight conversations có unread > 0"],
af:[],cat:"Admin - Chat"},
{id:"UC-72",name:"Open Conversation (Admin)",actors:["Admin","Manager"],pri:"High",
pre:"Conversation tồn tại",post:"Lịch sử chat hiển thị",
mf:["Admin click vào conversation","System gọi API GET /chat/convs/:id","System trả về messages[]","Admin đọc tin nhắn","System đánh dấu đã đọc (PATCH /chat/convs/:id/read)"],
af:[],cat:"Admin - Chat"},
{id:"UC-73",name:"Reply to Customer Chat",actors:["Admin","Manager"],pri:"High",
pre:"Conversation đang mở",post:"Tin nhắn reply được gửi",
mf:["Admin nhập reply","Admin bấm Send","System gọi API POST /chat/convs/:id/messages { senderType: manager, text }","System push message, tăng unread cho user","Customer thấy reply trong widget"],
af:[],cat:"Admin - Chat"},
{id:"UC-74",name:"Mark Conversation Read",actors:["Admin","Manager"],pri:"Low",
pre:"Conversation có unreadForManager > 0",post:"unreadForManager = 0",
mf:["Admin mở conversation","System tự động gọi PATCH /chat/convs/:id/read { target: manager }","unreadForManager reset về 0"],
af:[],cat:"Admin - Chat"},
{id:"UC-75",name:"Close Conversation",actors:["Admin","Manager"],pri:"Low",
pre:"Conversation đang mở",post:"Conversation status = CLOSED",
mf:["Admin bấm Close Chat","System gọi API PATCH /chat/convs/:id/close","System set status = CLOSED","Conversation không còn xuất hiện trong danh sách mở"],
af:[],cat:"Admin - Chat"}
);

// ===== GENERATE XML FILES =====
if (require.main === module) {
  ucs.forEach(function(uc) {
    var actors = uc.actors.map(function(a) { return "    <Actor>" + esc(a) + "</Actor>"; }).join("\n");
    var mainFlow = uc.mf.map(function(s,i) { return "    <Step number=\"" + (i+1) + "\">" + esc(s) + "</Step>"; }).join("\n");
    var altFlow = uc.af.map(function(s,i) { return "    <Alternative id=\"" + (i+1) + "\">" + esc(s) + "</Alternative>"; }).join("\n");
    var xml = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<UseCase id="' + esc(uc.id) + '" name="' + esc(uc.name) + '" category="' + esc(uc.cat) + '">',
      '  <Actors>',
      actors,
      '  </Actors>',
      '  <Priority>' + esc(uc.pri) + '</Priority>',
      '  <Precondition>' + esc(uc.pre) + '</Precondition>',
      '  <Postcondition>' + esc(uc.post) + '</Postcondition>',
      '  <MainFlow>',
      mainFlow,
      '  </MainFlow>',
      '  <AlternativeFlows>',
      altFlow,
      '  </AlternativeFlows>',
      '</UseCase>'
    ].join("\n");

    var safeName = uc.id + "-" + uc.name.replace(/[\\/:*?"<>|]/g, "-") + ".xml";
    fs.writeFileSync(path.join(BASE, safeName), xml, "utf8");
  });

  console.log("Generated " + ucs.length + " use case XML files in " + BASE);
}
